GOODREADS_CATEGORIES_URL = "https://www.goodreads.com/genres/list"

GOODREADS_LIST_TITLE_LINK = "//a[@class='listTitle']"
GOODREADS_LIST_CATE_XPATH = "//*[@id='bodycontainer']//*[@class='leftContainer']//div[@class='shelfStat']//a"
GOODREADS_NEXT_PAGE_CATE_XPATH = "//a[@rel='next' and contains(text(), 'next')]"
GOODREADS_LAST_PAGE_CATE_XPATH = "//a[@rel='next' and contains(text(), 'Next')]/preceding-sibling::a[1]"
GOODREADS_LINK_TO_FULL_LIST_BOOK_XPATH = "//a[starts-with(@href, '/shelf/show') and contains(text(), 'More')]"
GOODREADS_LIST_BOOK_XPATH = "//*[@id='bodycontainer']//a[@class='bookTitle']/parent::*/parent::*//a[starts-with(@href, '/book/show/') and @class='bookTitle']"
GOODREADS_TITLE_XPATH = "//h1"
GOODREADS_SERIES_XPATH = "//h1/preceding-sibling::h3"
GOODREADS_AUTHOR_XPATH = "//a[@class='ContributorLink']/*[text() and @data-testid='name'][not(following-sibling::*[text()])]"
GOODREADS_RELATED_PEOPLE_NAME_XPATH = "//a[@class='ContributorLink']/*[text() and @data-testid='name'][following-sibling::*[text()]]"
GOODREADS_RELATED_PEOPLE_POSITION_XPATH = "//a[@class='ContributorLink']/*[text() and @data-testid='name'][following-sibling::*[text()]]/following-sibling::*[text()]"
GOODREADS_EXPAND_AUTHOR_BTN_XPATH = "//div[@class='ContributorLinksList']//button"
GOODREADS_DESCRIPTION_XPATH = "//*[@data-testid='description']//span"
GOODREADS_EXPAND_GENRE_BTN_XPATH = "//*[@data-testid='genresList']//button"
GOODREADS_GENRE_LIST_XPATH = "//*[@data-testid='genresList']//a[contains(@href, '/genres')]"
GOODREADS_BOOK_NUM_PAGE = "//*[@class='BookDetails']//*[@class='FeaturedDetails']/*[@data-testid='pagesFormat']"
GOODREADS_BOOK_PUBLISH_YEAR = "//*[@class='BookDetails']//*[@class='FeaturedDetails']/*[@data-testid='publicationInfo']"
GOODREADS_BOOK_RATING = "//*[@class='RatingStatistics__rating']"
GOODREADS_BOOK_RATING_COUNT = "//*[@class='BookPageMetadataSection__ratingStats']//*[@data-testid='ratingsCount']"
GOODREADS_BOOK_BTN_EXPAND_EDITION = "//*[@class='BookDetails']//div[@class='Button__container']/button"
GOODREADS_BOOK_LANGUAGE = "//*[@class='DescListItem']/child::*[text()='Language']/following-sibling::*"